// <auto-generated />
using System;
using Fauno.Agenda.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fauno.Agenda.Infrastructure.Migrations
{
    [DbContext(typeof(AgendaDbContext))]
    partial class AgendaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Appointment", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<string>("AppointmentType")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Description")
                    .HasMaxLength(1000)
                    .HasColumnType("varchar(1000)");

                b.Property<DateTime>("End")
                    .HasColumnType("datetime(6)");

                b.Property<Guid>("OwnerId")
                    .HasColumnType("char(36)");

                b.Property<string>("OwnerName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("varchar(200)");

                b.Property<Guid>("PetId")
                    .HasColumnType("char(36)");

                b.Property<string>("PetName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("varchar(200)");

                b.Property<DateTime?>("RemovedAt")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("Start")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)");

                b.Property<string>("Title")
                    .HasMaxLength(200)
                    .HasColumnType("varchar(200)");

                b.Property<Guid>("VeterinarianId")
                    .HasColumnType("char(36)");

                b.Property<string>("VeterinarianName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("varchar(200)");

                b.HasKey("Id");

                b.ToTable("Appointments", (string)null);
            });

            modelBuilder.Entity("Fauno.Agenda.Domain.Entities.AvailabilityException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("VeterinarianId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("AvailabilityExceptions", (string)null);
                });

            modelBuilder.Entity("Fauno.Agenda.Domain.Entities.AvailabilityRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Recurrence")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SlotDurationMinutes")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("SlotEnd")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly>("SlotStart")
                        .HasColumnType("time(6)");

                    b.Property<Guid>("VeterinarianId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("AvailabilityRules", (string)null);
                });

            modelBuilder.Entity("Fauno.Agenda.Domain.Entities.AvailabilityRule", b =>
                {
                    b.OwnsOne("Fauno.Agenda.Domain.ValueObjects.PauseWindow", "Pause", b1 =>
                        {
                            b1.Property<Guid>("AvailabilityRuleId")
                                .HasColumnType("char(36)");

                            b1.Property<TimeOnly>("End")
                                .HasColumnType("time(6)")
                                .HasColumnName("PauseEnd");

                            b1.Property<TimeOnly>("Start")
                                .HasColumnType("time(6)")
                                .HasColumnName("PauseStart");

                            b1.HasKey("AvailabilityRuleId");

                            b1.ToTable("AvailabilityRules");

                            b1.WithOwner()
                                .HasForeignKey("AvailabilityRuleId");
                        });

                    b.Navigation("Pause");
                });
#pragma warning restore 612, 618
        }
    }
}
